### PR TITLE
fix(added generate-ant-design-css-vars script ): added a script to co…

### PR DESCRIPTION
**Pull request by Danishkhurshid**
…nvert json into css variables

### CODE REVIEW

**Comment by bmarshall511** [comment]
@Danishkhurshid Can we make it so we're not having to manually run a command? I was thinking it would be done dynamically during build. So running something maybe in layout that automatically parses then adds the needed vars globally vs us having to manually call it.

**Comment by Danishkhurshid** [comment]
Screenshot 2023-02-10 at 6 41 40 PM
@bmarshall511 don't think we can use any of the css-in-js library to dynamically add the generated styles inside the layout page. We can add the styles inside the client component Provider that then wraps the layout file.  

Example: 
```
import cagle from "../figma/cagle.json"
import { convertJsonToCssVariables } from "../generate-ant-design-css-vars"
const style = convertJsonToCssVariables(cagle);

export function Providers({
  children,
}: {
  children: ReactElement | ReactNode;
}) {
  return (
  <ConfigProvider>
     <style jsx global>{`
      ${style}
    `}</style>
    {children}
    </ConfigProvider>);
}

```

Let me know what how you want to go forward

**Comment by bmarshall511** [comment]
@Danishkhurshid works for me

**Comment by Danishkhurshid** [comment]
@bmarshall511 updated the PR. Please check.

**Review by bmarshall511 — APPROVED** [review]

**Pull request merged**
